# Generated by Django 5.2 on 2025-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season_number',
            field=models.IntegerField(db_index=True, verbose_name='Season Number'),
        ),
    ]
