# Generated by Django 5.1.8 on 2025-04-22 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_season_season_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItemSourceMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_last_updated_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of the last update received from this source for this item', null=True, verbose_name='Source Last Updated At')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_metadata', to='catalog.mediaitem', verbose_name='Media Item')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_metadata', to='catalog.source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Media Item Source Metadata',
                'verbose_name_plural': 'Media Item Source Metadata',
                'ordering': ['media_item', 'source'],
                'unique_together': {('media_item', 'source')},
            },
        ),
    ]
