# Generated by Django 5.1.8 on 2025-04-23 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_mediaitemsourcemetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024, unique=True, verbose_name='URL')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='catalog.episode', verbose_name='Episode')),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
                'ordering': ['episode', 'id'],
            },
        ),
    ]
