# Generated by Django 5.1.8 on 2025-04-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodik_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Kodik Translation ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='mediasourcelink',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Seen At'),
        ),
        migrations.AlterUniqueTogether(
            name='mediasourcelink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mediasourcelink',
            name='translation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='catalog.translation', verbose_name='Translation'),
        ),
        migrations.AlterUniqueTogether(
            name='mediasourcelink',
            unique_together={('episode', 'translation', 'source'), ('media_item', 'episode', 'translation', 'source')},
        ),
        migrations.AddConstraint(
            model_name='mediasourcelink',
            constraint=models.UniqueConstraint(condition=models.Q(('media_item__isnull', True), ('episode__isnull', False), ('translation__isnull', False)), fields=('episode', 'translation', 'source'), name='unique_episode_translation_source_link'),
        ),
        migrations.AddConstraint(
            model_name='mediasourcelink',
            constraint=models.UniqueConstraint(condition=models.Q(('media_item__isnull', False), ('episode__isnull', True), ('translation__isnull', False)), fields=('media_item', 'translation', 'source'), name='unique_mediaitem_translation_source_link'),
        ),
        migrations.RemoveField(
            model_name='mediasourcelink',
            name='translation_info',
        ),
    ]
