# Generated by Django 5.1.8 on 2025-04-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_translation_mediasourcelink_last_seen_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show'), ('anime_movie', 'Anime Movie'), ('anime_series', 'Anime Series'), ('cartoon_movie', 'Cartoon Movie'), ('cartoon_series', 'Cartoon Series'), ('documentary_movie', 'Documentary Movie'), ('documentary_series', 'Documentary Series'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30, verbose_name='Media Type'),
        ),
    ]
