# Generated by Django 5.1.8 on 2025-04-24 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_mediaitem_media_type'),
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedMediaPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, help_text='Optional title for this section.', max_length=150, verbose_name='Title')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='LatestMediaPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('latest_count', models.PositiveIntegerField(default=5, help_text='How many latest media items to show.', verbose_name='Number of items')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='MediaListByCriteriaPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, help_text='Optional title for this section.', max_length=150, verbose_name='Title')),
                ('media_type', models.CharField(blank=True, choices=[('movie', 'Movie'), ('tv_show', 'TV Show'), ('anime_movie', 'Anime Movie'), ('anime_series', 'Anime Series'), ('cartoon_movie', 'Cartoon Movie'), ('cartoon_series', 'Cartoon Series'), ('documentary_movie', 'Documentary Movie'), ('documentary_series', 'Documentary Series'), ('unknown', 'Unknown')], help_text='Leave blank for any type.', max_length=30, null=True, verbose_name='Filter by Media Type')),
                ('year_from', models.PositiveIntegerField(blank=True, help_text='Minimum release year.', null=True, verbose_name='Year From')),
                ('year_to', models.PositiveIntegerField(blank=True, help_text='Maximum release year.', null=True, verbose_name='Year To')),
                ('sort_by', models.CharField(choices=[('-updated_at', 'Recently Updated'), ('-created_at', 'Recently Added'), ('-release_year', 'Newest First'), ('release_year', 'Oldest First'), ('title', 'Title (A-Z)'), ('-title', 'Title (Z-A)')], default='-updated_at', max_length=50, verbose_name='Sort Order')),
                ('max_items', models.PositiveIntegerField(default=10, help_text='Maximum number of items to display in this list.', verbose_name='Maximum items')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveConstraint(
            model_name='mediasourcelink',
            name='unique_episode_translation_source_link',
        ),
        migrations.RemoveConstraint(
            model_name='mediasourcelink',
            name='unique_mediaitem_translation_source_link',
        ),
        migrations.AlterUniqueTogether(
            name='mediasourcelink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='featuredmediapluginmodel',
            name='items',
            field=models.ManyToManyField(help_text='Select the media items to feature.', to='catalog.mediaitem', verbose_name='Featured Items'),
        ),
        migrations.AddField(
            model_name='medialistbycriteriapluginmodel',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Show items matching ANY of these countries (leave blank for any).', to='catalog.country', verbose_name='Filter by Countries'),
        ),
        migrations.AddField(
            model_name='medialistbycriteriapluginmodel',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Show items matching ANY of these genres (leave blank for any).', to='catalog.genre', verbose_name='Filter by Genres'),
        ),
    ]
