# Generated by Django 5.1.8 on 2025-04-28 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_featuredmediapluginmodel_latestmediapluginmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Watched At')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewing_history', to='catalog.episode', verbose_name='Episode')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_history', to='catalog.mediasourcelink', verbose_name='Watched Link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Viewing History Entry',
                'verbose_name_plural': 'Viewing History',
                'ordering': ['-watched_at'],
                'unique_together': {('user', 'link')},
            },
        ),
    ]
