# Generated by Django 5.1.8 on 2025-04-28 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_favorite'),
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinueWatchingPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='Continue Watching', help_text='Optional title for this section.', max_length=150, verbose_name='Title')),
                ('items_count', models.PositiveIntegerField(default=5, help_text='Maximum number of different shows/movies to display.', verbose_name='Number of items')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
