# Generated by Django 5.1.8 on 2025-04-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_continuewatchingpluginmodel'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediaitem',
            name='unique_kinopoisk_id',
        ),
        migrations.RemoveConstraint(
            model_name='mediaitem',
            name='unique_imdb_id',
        ),
        migrations.RemoveConstraint(
            model_name='mediaitem',
            name='unique_shikimori_id',
        ),
        migrations.RemoveConstraint(
            model_name='mediaitem',
            name='unique_mydramalist_id',
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='IMDb ID'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='kinopoisk_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Kinopoisk ID'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='mydramalist_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='MyDramaList ID'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='shikimori_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Shikimori ID'),
        ),
    ]
